//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vdr
    {
        public string rowid { get; set; }
        public string VdrNo { get; set; }
        public string VdrNa { get; set; }
        public string VdrId { get; set; }
        public string VdrTel { get; set; }
        public string VdrRmaTel { get; set; }
        public string VdrSalNa { get; set; }
        public string VdrSalTel { get; set; }
        public string VdrUrl { get; set; }
        public string VdrAdr { get; set; }
        public string VdrDtPay { get; set; }
        public Nullable<System.DateTime> VdrDtC { get; set; }
        public Nullable<System.DateTime> VdrDtM { get; set; }
        public string VdrRk { get; set; }
        public bool VdrEn { get; set; }
    }
}
